name: 'Bump Version'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@latest'
        with:
          tag-prefix: 'v'
          major-wording: 'major,Major,breaking,Breaking'
          minor-wording: 'minor,Minor,feat,Feat,feature,Feature'
          patch-wording: 'patch,Patch,fix,Fix,fixes,Fixes'
          rc-wording: 'rc,pre,beta,alpha'  # For pre-releases
          commit-message: 'ci: bump version to {{version}} [skip ci]'  # Skips re-triggering
          push: true  # Pushes the commit/tag back to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
